const fs = require('fs');

const generateWorldReplacement = [
"    generateWorld: (countryIds, mode, year) => {",
"      const countryId = countryIds[0];",
"      const country = window.CXICore?.COUNTRIES?.find(c => c.id === countryId) || window.CXICore?.COUNTRIES?.[0] || { id: 'england', name: 'England' };",
"      ",
"      const divisions = {};",
"      const generatedClubs = {};",
"      ",
"      let seed = 0;",
"      for (let i = 0; i < country.name.length; i++) seed += country.name.charCodeAt(i);",
"      const random = () => {",
"        let x = Math.sin(seed++) * 10000;",
"        return x - Math.floor(x);",
"      };",
"      ",
"      const realData = {",
"        'england': {",
"          leagues: ['Premier League', 'Championship', 'League One'],",
"          clubs: [",
"            ['Arsenal', 'ARS', '#ef0107', '#ffffff', 88], ['Aston Villa', 'AVL', '#670e36', '#95bfe5', 82], ['Bournemouth', 'BOU', '#b50e12', '#000000', 76],",
"            ['Brentford', 'BRE', '#e30613', '#ffffff', 77], ['Brighton', 'BHA', '#0057b8', '#ffffff', 80], ['Chelsea', 'CHE', '#034694', '#ffffff', 85],",
"            ['Crystal Palace', 'CRY', '#1b458f', '#a7a5a6', 78], ['Everton', 'EVE', '#003399', '#ffffff', 79], ['Fulham', 'FUL', '#ffffff', '#000000', 78],",
"            ['Liverpool', 'LIV', '#c8102E', '#ffffff', 89], ['Luton Town', 'LUT', '#f78f1e', '#000099', 74], ['Man City', 'MCI', '#6cabdd', '#ffffff', 91],",
"            ['Man United', 'MUN', '#da291c', '#ffffff', 86], ['Newcastle', 'NEW', '#000000', '#ffffff', 83], ['Nottm Forest', 'NFO', '#dd0000', '#ffffff', 76],",
"            ['Sheff Utd', 'SHU', '#ee2737', '#000000', 74], ['Tottenham', 'TOT', '#132257', '#ffffff', 85], ['West Ham', 'WHU', '#7a263a', '#1bb1e7', 81],",
"            ['Wolves', 'WOL', '#fdb913', '#000000', 78], ['Burnley', 'BUR', '#6c1d45', '#99d6ea', 75]",
"          ]",
"        },",
"        'spain': {",
"          leagues: ['La Liga', 'Segunda Division', 'Primera Federacion'],",
"          clubs: [",
"            ['Real Madrid', 'RMA', '#ffffff', '#000000', 92], ['Barcelona', 'BAR', '#004d98', '#a50044', 90], ['Atletico Madrid', 'ATM', '#cb3524', '#ffffff', 87],",
"            ['Sevilla', 'SEV', '#ffffff', '#d11010', 82], ['Real Sociedad', 'RSO', '#0067b1', '#ffffff', 83], ['Athletic Club', 'ATH', '#ee2523', '#ffffff', 81],",
"            ['Real Betis', 'BET', '#0bb363', '#ffffff', 80], ['Villarreal', 'VIL', '#fce216', '#000000', 81], ['Valencia', 'VAL', '#ffffff', '#000000', 79],",
"            ['Girona', 'GIR', '#ce181e', '#ffffff', 78], ['Osasuna', 'OSA', '#d61120', '#0a2340', 77], ['Celta Vigo', 'CEL', '#a9d0f5', '#ffffff', 76],",
"            ['Mallorca', 'MAL', '#e01e26', '#000000', 76], ['Getafe', 'GET', '#004f9f', '#ffffff', 75], ['Rayo Vallecano', 'RAY', '#ffffff', '#e01e26', 75],",
"            ['Las Palmas', 'LPA', '#ffd700', '#0000ff', 74], ['Alaves', 'ALA', '#0000ff', '#ffffff', 74], ['Cadiz', 'CAD', '#ffeb00', '#0000ff', 73],",
"            ['Almeria', 'ALM', '#ee1c25', '#ffffff', 73], ['Granada', 'GRA', '#c8102e', '#ffffff', 73]",
"          ]",
"        },",
"        'germany': {",
"          leagues: ['Bundesliga', '2. Bundesliga', '3. Liga'],",
"          clubs: [",
"            ['Bayern Munich', 'BAY', '#dc052d', '#ffffff', 91], ['Dortmund', 'DOR', '#fde100', '#000000', 86], ['Bayer Leverkusen', 'B04', '#e32221', '#000000', 87],",
"            ['RB Leipzig', 'RBL', '#dd013f', '#ffffff', 85], ['Stuttgart', 'VFB', '#e32219', '#ffffff', 82], ['Eintracht Frankfurt', 'SGE', '#000000', '#e1000f', 81],",
"            ['Freiburg', 'SCF', '#000000', '#ffffff', 80], ['Hoffenheim', 'TSG', '#003fa4', '#ffffff', 79], ['Wolfsburg', 'WOB', '#009d00', '#ffffff', 78],",
"            ['Monchengladbach', 'BMG', '#000000', '#ffffff', 78], ['Werder Bremen', 'SVW', '#008e54', '#ffffff', 77], ['Augsburg', 'FCA', '#ba3733', '#ffffff', 76],",
"            ['Heidenheim', 'FCH', '#e2001a', '#ffffff', 75], ['Bochum', 'BOC', '#005ca9', '#ffffff', 75], ['Mainz 05', 'M05', '#ed1c24', '#ffffff', 75],",
"            ['Union Berlin', 'FCU', '#d20014', '#f6e118', 76], ['Koln', 'KOE', '#ed1c24', '#ffffff', 75], ['Darmstadt', 'SVD', '#004a99', '#ffffff', 73],",
"            ['Schalke 04', 'S04', '#004d9d', '#ffffff', 74], ['Hamburger SV', 'HSV', '#004183', '#ffffff', 75]",
"          ]",
"        },",
"        'italy': {",
"          leagues: ['Serie A', 'Serie B', 'Serie C'],",
"          clubs: [",
"            ['Inter Milan', 'INT', '#00529f', '#000000', 89], ['AC Milan', 'ACM', '#fb090b', '#000000', 86], ['Juventus', 'JUV', '#000000', '#ffffff', 87],",
"            ['Napoli', 'NAP', '#12a0d7', '#ffffff', 86], ['AS Roma', 'ROM', '#8e1f2f', '#f0bc42', 84], ['Lazio', 'LAZ', '#87d8f7', '#ffffff', 83],",
"            ['Atalanta', 'ATA', '#1b4a8e', '#000000', 84], ['Fiorentina', 'FIO', '#482e92', '#ffffff', 81], ['Torino', 'TOR', '#8a1e36', '#ffffff', 79],",
"            ['Bologna', 'BOL', '#1c2e4a', '#a6172d', 80], ['Genoa', 'GEN', '#a31f31', '#112242', 77], ['Monza', 'MON', '#e31837', '#ffffff', 77],",
"            ['Lecce', 'LEC', '#f3db00', '#db0d15', 76], ['Sassuolo', 'SAS', '#000000', '#009640', 76], ['Empoli', 'EMP', '#00529b', '#ffffff', 75],",
"            ['Udinese', 'UDI', '#000000', '#ffffff', 76], ['Cagliari', 'CAG', '#00254c', '#a51829', 75], ['Verona', 'VER', '#00295d', '#ffdf00', 75],",
"            ['Frosinone', 'FRO', '#fbbc05', '#003a80', 74], ['Salernitana', 'SAL', '#6b1129', '#ffffff', 73]",
"          ]",
"        },",
"        'france': {",
"          leagues: ['Ligue 1', 'Ligue 2', 'Championnat National'],",
"          clubs: [",
"            ['PSG', 'PSG', '#004170', '#da291c', 90], ['Monaco', 'MON', '#cc0000', '#ffffff', 84], ['Marseille', 'OM', '#00aae4', '#ffffff', 83],",
"            ['Lille', 'LIL', '#d82833', '#ffffff', 82], ['Lens', 'RCL', '#ed1c24', '#ffea00', 81], ['Lyon', 'OL', '#ffffff', '#0055a4', 80],",
"            ['Rennes', 'REN', '#e30613', '#000000', 80], ['Nice', 'NIC', '#ed1b24', '#000000', 79], ['Reims', 'SDR', '#ed1c24', '#ffffff', 77],",
"            ['Strasbourg', 'RCSA', '#0072b2', '#ffffff', 77], ['Montpellier', 'MHSC', '#003366', '#ff6600', 76], ['Toulouse', 'TFC', '#512a84', '#ffffff', 76],",
"            ['Nantes', 'FCN', '#fcd116', '#008751', 75], ['Le Havre', 'HAC', '#0000ff', '#87ceeb', 75], ['Metz', 'FCM', '#6d28d9', '#ffffff', 74],",
"            ['Clermont', 'CF63', '#a70014', '#003a80', 74], ['Lorient', 'FCL', '#f77f00', '#000000', 74], ['Brest', 'SB29', '#e30613', '#ffffff', 78],",
"            ['Bordeaux', 'FCGB', '#002f5d', '#ffffff', 73], ['Saint-Etienne', 'ASSE', '#008000', '#ffffff', 74]",
"          ]",
"        }",
"      };",
"",
"      const prefixes = ['Real', 'Sporting', 'Racing', 'Athletic', 'Dynamo', 'Spartak', 'Inter', 'AC', 'FC', 'United', 'City', 'Rovers', 'Wanderers', 'Boys', 'Locomotive', 'Olympique'];",
"      const suffixes = ['FC', 'United', 'City', 'Rovers', 'Wanderers', 'Athletic', 'Club', 'Town', 'Villa', 'Palace', 'Star', 'Victory'];",
"",
"      const countryData = realData[country.id];",
"      const maxDivs = countryData ? countryData.leagues.length : 3;",
"",
"      for (let level = 1; level <= maxDivs; level++) {",
"        let divId = 'div' + level;",
"        let divName = countryData ? countryData.leagues[level-1] : (level === 1 ? country.name + ' Premier League' : level === 2 ? country.name + ' Championship' : country.name + ' League One');",
"        let clubIds = [];",
"        ",
"        let clubsToGen = 18; // standard size",
"        ",
"        for (let i = 0; i < clubsToGen; i++) {",
"          let cid = 'c_' + country.id + '_' + level + '_' + i;",
"          clubIds.push(cid);",
"          ",
"          let name, abbr, primary, secondary, rep;",
"          ",
"          if (countryData && countryData.clubs && level === 1 && i < countryData.clubs.length) {",
"             let cdata = countryData.clubs[i];",
"             name = cdata[0];",
"             abbr = cdata[1];",
"             primary = cdata[2];",
"             secondary = cdata[3];",
"             rep = cdata[4];",
"          } else {",
"             let p = prefixes[Math.floor(random() * prefixes.length)];",
"             let s = suffixes[Math.floor(random() * suffixes.length)];",
"             let nameType = Math.floor(random() * 3);",
"             if (nameType === 0) name = p + ' ' + (countryData ? 'City ' + i : country.name);",
"             else if (nameType === 1) name = (countryData ? 'Town ' + i : country.name) + ' ' + s;",
"             else name = p + ' ' + s + ' ' + Math.floor(random()*100);",
"             ",
"             if (i === 0 && level === 1 && !countryData) name = country.name + ' National Club';",
"             abbr = name.substring(0,3).toUpperCase();",
"             ",
"             let r1 = Math.floor(random()*255).toString(16).padStart(2,'0');",
"             let g1 = Math.floor(random()*255).toString(16).padStart(2,'0');",
"             let b1 = Math.floor(random()*255).toString(16).padStart(2,'0');",
"             primary = '#' + r1 + g1 + b1;",
"             ",
"             let r2 = Math.floor(random()*255).toString(16).padStart(2,'0');",
"             let g2 = Math.floor(random()*255).toString(16).padStart(2,'0');",
"             let b2 = Math.floor(random()*255).toString(16).padStart(2,'0');",
"             secondary = '#' + r2 + g2 + b2;",
"             ",
"             rep = 75 - (level * 10) - Math.floor(random() * 10);",
"          }",
"          ",
"          generatedClubs[cid] = {",
"            id: cid,",
"            name: name,",
"            abbr: abbr,",
"            primary: primary,",
"            secondary: secondary,",
"            countryId: country.id,",
"            divisionId: divId,",
"            divisionLevel: level,",
"            reputation: rep",
"          };",
"        }",
"        ",
"        divisions[divId] = { id: divId, name: divName, level: level, clubIds: clubIds };",
"      }",
"      ",
"      return {",
"        countries: { [country.id]: country },",
"        divisions: divisions,",
"        clubs: generatedClubs,",
"        players: {}",
"      };",
"    },"
].join('\\n');

let content = fs.readFileSync('game.js', 'utf-8');
content = content.replace(/    generateWorld: \(countryIds, mode, year\) => \{[\s\S]*?    \},/m, generateWorldReplacement);
fs.writeFileSync('game.js', content, 'utf-8');
console.log('Successfully injected leagues.');
