const fs=require('fs'),vm=require('vm');
const game=fs.readFileSync('game.js','utf8'),html=fs.readFileSync('index.html','utf8');
function fn(name){const m=`function ${name}(`,st=game.indexOf(m);if(st<0)throw Error(name);const b=game.indexOf('{',st);let d=0,q=null,e=false;for(let i=b;i<game.length;i++){const c=game[i];if(q){if(e){e=false;continue}if(c==='\\'){e=true;continue}if(c===q)q=null;continue}if(c==='"'||c==="'"||c==='`'){q=c;continue}if(c==='{')d++;else if(c==='}'&&--d===0)return game.slice(st,i+1)}throw Error('unclosed '+name)}
const C=[];const ck=(n,v)=>C.push([n,!!v]);
ck('v57 marker',game.includes("v57.0-tactical-vision-scan-pass-unlock"));ck('cache bust',html.includes('game.js?v=57.0.0')&&html.includes('styles.css?v=57.0.0'));ck('scan non-blocking',fn('tacticalPerformScan').includes('awareness event, NOT a blocking game state'));ck('vision queue enabled',game.includes("visionQueue=incoming&&t.drill==='mental'&&t.scanUsed"));ck('receipt unlocks controls',game.includes('t.userReadyToPass=true;t.passControlsEnabled=true;t.passUnlockAt=now'));ck('stale owner recovery before gating',fn('tacticalUserAction').indexOf('possession recovery happens BEFORE')<fn('tacticalUserAction').indexOf("if(t.drill==='mental'&&incoming)"));ck('pass target score is mutable',fn('tacticalChoosePassTarget').includes(';let score=')&&!fn('tacticalChoosePassTarget').includes(',score=-diff'));ck('best target is mutable',fn('tacticalChoosePassTarget').includes('let best=null,bestScore=-999'));
let now=1000;const career={player:{attrs:{vision:86,decisions:84,composure:81,firstTouch:84,technique:82,balance:74,strength:67,passing:88,finishing:65}}};const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t;
const x={performance:{now:()=>now},console,career,window:{},document:{querySelectorAll:()=>[]},setTimeout:f=>{f();return 0},clearTimeout:()=>{},clamp,lerp,$:()=>null,tacticalStreakMultiplier:()=>1,tacticalFeedback:()=>{},tacticalUpdateControlState:()=>{},tacticalScore:()=>{},tacticalSetState:(s,state,o,d)=>{s.tactical.state=state;s.tactical.stateAge=0;s.tactical.objective=o;s.tactical.detail=d},tacticalScheduleScenarioReset:(s,delay,r)=>{s.tactical.resetQueued=now+delay;s.tactical.resetReason=r},tacticalFootBallAnchor:(s,a)=>({x:a.x,y:a.y+3.4,z:0}),tacticalReleaseBall:(s,a,t,action)=>{s.tactical.ownerId=null;s.player.hasBall=false;s.ball.free=true;s.ball.status='released';s.ball.x=a.x;s.ball.y=a.y;s.ball.intendedId=t===s.player?'user':t.tacticalId;s.ball.intendedTeam=t.team??0;s.ball.releaseAge=0;s.ball.incomingSpeed=32;s.tactical.passFlight={startedAt:now,resolved:false};return true},tacticalMoveActor:(p,xx,yy,dt,sp)=>{const dx=xx-p.x,dy=yy-p.y,d=Math.hypot(dx,dy)||1;p.x+=dx/d*sp*dt;p.y+=dy/d*sp*dt},tacticalNearestActorToBall:s=>[s.player,...s.tactical.mates,...s.tactical.opponents].sort((a,b)=>Math.hypot(a.x-s.ball.x,a.y-s.ball.y)-Math.hypot(b.x-s.ball.x,b.y-s.ball.y))[0],tacticalResolvePassFlight:(s,a)=>{if(s.tactical.passFlight)s.tactical.passFlight.resolved=true},setTrainingVisualAction:()=>{},beep:()=>{},trainingGameState:null};vm.createContext(x);for(const n of ['distancePointToSegment','tacticalVisionAssessOptions','tacticalVisionBuildScanSnapshot','tacticalVisionSetDefenderRoles','tacticalVisionDecisionWindow','tacticalVisionIncomingProgress','tacticalBeginNextVisionScenario','tacticalFailVisionPass','tacticalVisionPassWatchdog','tacticalOnPossession','tacticalChoosePassTarget','tacticalExecuteUserAction','tacticalConsumeBufferedAction','tacticalUserAction','tacticalPerformScan','tacticalUpdateVision'])vm.runInContext(fn(n),x);x.tacticalActorToken=(s,a)=>a===s.player?'user':a?.tacticalId||null;x.tacticalOwner=s=>s.tactical.ownerId==='user'?s.player:[...s.tactical.mates,...s.tactical.opponents].find(p=>p.tacticalId===s.tactical.ownerId)||null;x.tacticalGiveBall=(s,a,r)=>{s.tactical.mates.forEach(p=>p.hasBall=false);s.tactical.opponents.forEach(p=>p.hasBall=false);s.ball.free=false;s.ball.status='owned';s.ball.intendedId=null;s.tactical.ownerId=a===s.player?'user':a.tacticalId;s.tactical.possessionTeam=a.team??0;s.player.hasBall=a===s.player;if(a!==s.player)a.hasBall=true;x.tacticalOnPossession(s,a,r);if(a===s.player&&s.tactical.bufferedAction)x.tacticalConsumeBufferedAction(s)};
function state(){const p={x:50,y:70,team:0,hasBall:false,dir:-1.57,vx:0,vy:0},m=[{x:24,y:71,team:0,tacticalId:'m0'},{x:76,y:67,team:0,tacticalId:'m1'},{x:36,y:40,team:0,tacticalId:'m2'},{x:67,y:34,team:0,tacticalId:'m3'}],o=[{x:42,y:57,team:1,tacticalId:'o0'},{x:59,y:58,team:1,tacticalId:'o1'},{x:48,y:48,team:1,tacticalId:'o2'},{x:72,y:47,team:1,tacticalId:'o3'},{x:28,y:49,team:1,tacticalId:'o4'}];const s={player:p,keys:new Set(),teammates:[...m,...o],ball:{free:false,status:'owned',x:24,y:71,z:0},tactical:{drill:'mental',countdown:0,state:'WAITING_FOR_PASS',stateAge:.3,deliveryReleased:false,scanUsed:false,mates:m,opponents:o,difficulty:{pressure:.78,assist:.58},dynamicIntensity:1,metrics:{scans:0,perfectScans:0,noScans:0,firstTouches:0,poor:0,dispossessed:0,incomingInterceptions:0},ownerId:'m0',passer:m[0],goodOptions:[],bufferedAction:null,bufferedAt:0,lastInputAt:0,xp:{}}};x.tacticalVisionAssessOptions(s);x.tacticalVisionSetDefenderRoles(s,2);return s}
{const s=state();x.trainingGameState=s;x.tacticalUpdateVision(s,.016);s.tactical.stateAge=.31;s.ball.x=39;s.ball.y=70;now+=200;x.tacticalPerformScan(s);ck('scan keeps incoming state',s.tactical.state==='PRE_RECEIVE_SCAN'&&Math.abs(s.tactical.stateAge-.31)<1e-9);now+=200;x.tacticalGiveBall(s,s.player,'intended');ck('receive opens decision',s.tactical.ownerId==='user'&&s.tactical.state==='DECISION_WINDOW');x.tacticalUserAction(s,'j');ck('J after scan works',s.tactical.state==='PASS_RESOLUTION'&&s.ball.free&&s.ball.intendedId!=='user')}
{const s=state();x.trainingGameState=s;x.tacticalUpdateVision(s,.016);s.ball.x=42;s.ball.y=70;now+=200;x.tacticalPerformScan(s);x.tacticalUserAction(s,'j');const q=s.tactical.bufferedAction==='j';now+=160;x.tacticalGiveBall(s,s.player,'intended');ck('queue after scan works',q&&s.tactical.state==='PASS_RESOLUTION'&&s.ball.free)}
{const s=state();x.trainingGameState=s;s.tactical.scanUsed=true;s.tactical.state='DECISION_WINDOW';s.tactical.ownerId=null;s.player.hasBall=true;s.ball.free=false;s.ball.x=50;s.ball.y=73.4;x.tacticalUserAction(s,'j');ck('stale owner repaired',s.tactical.state==='PASS_RESOLUTION'&&s.ball.free)}
{let ok=true;for(let i=0;i<50;i++){const s=state();x.trainingGameState=s;x.tacticalUpdateVision(s,.016);s.ball.x=41;s.ball.y=70;now+=180;x.tacticalPerformScan(s);now+=190;x.tacticalGiveBall(s,s.player,'intended');x.tacticalUserAction(s,'j');if(s.tactical.state!=='PASS_RESOLUTION'||!s.ball.free){ok=false;break}}ck('50 cycles no pass lock',ok)}
let pass=0;for(const [n,v] of C){console.log(v?'PASS':'FAIL',n);if(v)pass++}console.log(`\nTactical Vision v57: ${pass}/${C.length} checks passed`);if(pass!==C.length)process.exit(1);
